### ISSUE TITLE
Typo in the ID of iTerm config symlinking step

### ISSUE THREAD

**Issue by connormason** [danielmmetz/dotfiles#1]
Found an extremely high priority bug I think will need resolution before EOD, the iterm symlinking step is named `Ensure gitconfig is symlinked`. Obviously this is going to break prod so we need a fix ASAP, pinging current on-call [@matthewgrossman](https://github.com/matthewgrossman)

```
Ensure gitconfig is symlinked:
  file.symlink:
    - name: {{ grains.home }}/Library/Preferences/com.googlecode.iterm2.plist
    - target: {{ grains.states_dir }}/macos/iterm2/com.googlecode.iterm2.plist
    - force: True
    - user: {{ grains.user }}
```

**Comment by matthewgrossman** [comment]
Hmm seems like a sev0, might need to loop in consultants for this one. @danielmmetz if we can't this fixed ASAP we will be pursuing legal action.

Thoughts on rewriting in a moral language like rust?

**Comment by danielmmetz** [comment]
Thanks for finding this! Addressed with https://github.com/danielmmetz/dotfiles/commit/e47d9fd0d9a43dab0a0a3926c91189675487a270

**Comment by danielmmetz** [comment]
As for the re-write, the trunk under states/nixos is what I've currently been using. I'm currently working on migrating it to a dotfile manager of my own (https://github.com/danielmmetz/settle).
